"""
100 days of Python course
DAY 10
"""

def is_leap(year):
    """

    Parameters
    ----------
    year : TYPE
        DESCRIPTION.

    Returns
    -------
    bool
        DESCRIPTION.

    """
    if year % 4 == 0:
        if year % 100 == 0:
            if year % 400 == 0:
                return True
            else:
                return False
        else:
            return True
    else:
        return False

def days_in_month(year, month):
    """

    Parameters
    ----------
    year : TYPE
        DESCRIPTION.
    month : TYPE
        DESCRIPTION.

    Returns
    -------
    TYPE
        DESCRIPTION.

    """
    month_days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    if month > 12 or month < 1:
        return "Invalid month entered."
    if month == 2 and is_leap(year):
        return 29
    return month_days[month - 1]



year = int(input("Enter a year (numeric): "))
month = int(input("Enter a month (numeric): "))
days = days_in_month(year, month)
print(days)

# note that refactor and warning messages generated by pylint
# which are outside the scope of this lesson: the program runs
# without errors
